package: text_to_speech
version: '1.0.0-dev-2024-09-28'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/text_to_speech


requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.16

page:
    title: translate:text_to_speech_title
    prio: 100
    icon: rex-icon fa-gear

# default_config:
#     field: 'Test'

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
